### ISSUE TITLE
What is the difference betwen rpmfusion's chromium-vaapi and Fedora's chromium build since they integrated vaapi patches?

### ISSUE THREAD

**Issue by sheepdestroyer** [biswasab/chromium_vaapi_fed#11]
It was reported that Fedora now builds chromium with vaapi patches.
I installed fedora's chromium and got accelerated video decoding working.

What are the differences/advantages, if any, still remaining with this repo compared to Fedora's build?

**Comment by qnixsynapse** [comment]
@sheepdestroyer  I was intended to discontinue chromium-vaapi build after Fedora chromium's got vaapi however people requested me to keep maintaining it.

* Much faster updates than Fedora
* Fedora's chromium uses a hack to separate the legal video codecs out and this hack causes the browser to become slow(if you're using HDD). Also upstream doesn't support this.
* Separating this cause the browser to break down into individual components. So GSSAPI requests crashes the browser and there is no way to fix it. (There is a bug report)
* RPMFusion's chromium uses clang instead of GCC which Fedora's chromium uses.

These are few basic differences.
