### ISSUE TITLE
vaapi fails

### ISSUE THREAD

**Issue by sheepdestroyer** [biswasab/chromium_vaapi_fed#5]
fedora 28, last available copr build

intel IvyBridge HD4000

when starting, chromium gives : 
````
[7683:7683:0809/202733.744540:ERROR:vaapi_wrapper.cc(577)] vaQueryConfigEntrypoints failed VA error: the requested VAProfile is not supported
[7683:7683:0809/202733.744603:ERROR:vaapi_wrapper.cc(577)] vaQueryConfigEntrypoints failed VA error: the requested VAProfile is not supported
[7683:7683:0809/202733.777525:ERROR:sandbox_linux.cc(378)] InitializeSandbox() called with multiple threads in process gpu-process.
````
In chrome://gpu/ : Video Decode: Hardware accelerated

my gpu doesn't support accelerated vp9 so I installed  the extension h264ify to 
 force youtube video in h264 : https://github.com/erkserkserks/h264ify

The problem is youtube now saying : "Your browser does not currently recognize any of the formats available"

![image](https://user-images.githubusercontent.com/1377479/43896509-048d4714-9c14-11e8-8c2d-88644c0959bc.png)

**Comment by qnixsynapse** [comment]
You need to install chromium-lib-media-freeworld from my gitlab [repo](https://gitlab.com/biswasab/chromium_vaapi_fed/-/jobs/87637666/artifacts/file/public/x86_64/chromium-libs-media-freeworld-68.0.3440.84-1.fc28.chromium_vaapi.x86_64.rpm). 
Also h264ify extension will disable vpx decoder and since h264 is a proprietary format I have moved it into a separate package. 

Edit: That vaapi error is because some of the profiles are not supported by the browser for e.g mpeg
Here, is my chrome://gpu on nvidia.
![screenshot from 2018-08-09 18-51-47](https://user-images.githubusercontent.com/17230826/43901661-a3131378-9c05-11e8-98a5-bb33b0bde18b.png)

**Comment by sheepdestroyer** [comment]
seems to work : 
Video Acceleration Information
Decode h264 baseline | up to 4096x4096 pixels
Decode h264 main | up to 4096x4096 pixels
Decode h264 high | up to 4096x4096 pixels

Thanks for your great work

**Comment by qnixsynapse** [comment]
Remember you have to update chromium-libs-media-freeworld each time chromium updates. Sorry but copr doesn't allow to host restricted codecs. Not even openh264. :(
